"""Self-driving, paced customer-support session for screen recording.

Every line below is a REAL call into the agent's brain (SynapCores):

    recall memory   → vector search over past turns      (give-any-agent-long-term-memory)
    retrieve KB     → RAG over the knowledge base         (rag-ground-any-agent)
    semantic route  → pick a tool by meaning              (semantic-tool-routing)
    act             → run the chosen tool                 (build-a-customer-support-agent)
    GENERATE reply  → grounded generation                 (build-a-customer-support-agent)
    write memory    → persist the turn for next time      (give-any-agent-long-term-memory)

Nothing is faked. The transcript prints, per turn:

    you>   <the customer line>
           recall=N kb=M route=[tool=score,...] -> chosen_tool
    agent> <the grounded reply>

For this recording the brain runs on a PRODUCTION OpenAI configuration:
  * memory recall + RAG + tool-routing use OpenAI text-embedding (1536-dim),
    served through the SynapCores gateway's EMBED() / COSINE_SIMILARITY() surface
    (the cognition is the database), and
  * the reply is generated by OpenAI gpt-4o, called directly via the OpenAI API
    — the LLM is a pluggable component, swappable for any provider. (In the
    zero-key bundled build the reply is the engine's own GENERATE; see
    ../docs/PRODUCTION.md.)

The key is read once from the OPENAI_API_KEY environment variable and is never
printed. The identical agent runs with ZERO external key on the bundled model
(see ../PRODUCTION.md) — only the gateway's provider config changes.
"""

from __future__ import annotations

import json
import os
import sys
import time
import urllib.error
import urllib.request

from synapcores_agent import Config, SupportAgent
from synapcores_agent.agent import SYSTEM_PERSONA
from synapcores_agent.seed import seed

# ----------------------------------------------------------------------------
# Production generator: OpenAI gpt-4o. We override ONLY the GENERATE step; every
# other step (recall, RAG, route, memory write) stays a real SynapCores call.
# ----------------------------------------------------------------------------
OPENAI_MODEL = "gpt-4o"
_OPENAI_KEY = os.environ.get("OPENAI_API_KEY", "")


def gpt4o(prompt: str) -> str:
    """Call OpenAI gpt-4o for the grounded reply. Key comes from the env only."""
    if not _OPENAI_KEY:
        raise SystemExit("OPENAI_API_KEY not set in the environment.")
    body = {
        "model": OPENAI_MODEL,
        "messages": [
            {"role": "system", "content": SYSTEM_PERSONA},
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.3,
        "max_tokens": 220,
    }
    req = urllib.request.Request(
        "https://api.openai.com/v1/chat/completions",
        data=json.dumps(body).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {_OPENAI_KEY}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    raw = urllib.request.urlopen(req, timeout=120).read().decode("utf-8")
    data = json.loads(raw)
    return data["choices"][0]["message"]["content"].strip()


# ----------------------------------------------------------------------------
# Terminal "typing" effects so the asciinema timing reads like a human session.
# ----------------------------------------------------------------------------
def _type(text: str, cps: float = 45.0, newline: bool = True) -> None:
    delay = 1.0 / cps
    for ch in text:
        sys.stdout.write(ch)
        sys.stdout.flush()
        time.sleep(delay)
    if newline:
        sys.stdout.write("\n")
        sys.stdout.flush()


def _pause(seconds: float) -> None:
    time.sleep(seconds)


GREEN = "\033[32m"
CYAN = "\033[36m"
DIM = "\033[2m"
BOLD = "\033[1m"
YELLOW = "\033[33m"
RESET = "\033[0m"


def run_turn(agent: SupportAgent, user_id: str, user_line: str, *, beat: str = "") -> None:
    """Drive one real agent turn and narrate the brain working."""
    # The customer "types".
    sys.stdout.write(f"{BOLD}you>{RESET} ")
    sys.stdout.flush()
    _type(user_line, cps=42)
    _pause(0.5)

    # --- real brain steps (all hit SynapCores / OpenAI) -------------------
    recalled = agent.brain.recall_memory(user_line, user_id, k=4)
    kb_hits = agent.brain.search_kb(user_line, k=3)
    tool, score, ranked = agent.router.route(user_line)

    grounding_blocks = []
    if kb_hits:
        from synapcores_agent.tools.support_tools import _format_docs

        grounding_blocks.append("Knowledge base articles:\n" + _format_docs(kb_hits))
    tool_summary = ""
    if tool is not None:
        result = tool.run(user_line, agent.brain, {"user_id": user_id})
        tool_summary = result.summary
        if result.grounding:
            grounding_blocks.append(result.grounding)

    # --- compact brain trace ---------------------------------------------
    route_str = ", ".join(f"{n}={s:.2f}" for n, s in ranked)
    recall_color = YELLOW if recalled else DIM
    _pause(0.3)
    sys.stdout.write(
        f"     {DIM}brain:{RESET} "
        f"{recall_color}recall={len(recalled)}{RESET} "
        f"{CYAN}kb={len(kb_hits)}{RESET} "
        f"{DIM}route=[{route_str}]{RESET} -> {BOLD}{tool.name if tool else 'none'}{RESET}\n"
    )
    sys.stdout.flush()

    # If memory was recalled, surface WHAT was remembered (the "it remembered" beat).
    if recalled:
        top = recalled[0]
        snippet = top["content"]
        if len(snippet) > 76:
            snippet = snippet[:76] + "..."
        _pause(0.2)
        sys.stdout.write(
            f"     {DIM}remembered [{top.get('score', 0):.2f}] "
            f"({top['role']}): {snippet}{RESET}\n"
        )
        sys.stdout.flush()

    if beat:
        _pause(0.2)
        sys.stdout.write(f"     {DIM}{beat}{RESET}\n")
        sys.stdout.flush()

    # --- grounded GENERATE with gpt-4o -----------------------------------
    _pause(0.4)
    sys.stdout.write(f"     {DIM}...thinking (gpt-4o){RESET}")
    sys.stdout.flush()
    prompt = agent._build_prompt(user_line, recalled, grounding_blocks)
    reply = gpt4o(prompt)
    sys.stdout.write("\r\033[K")  # clear the whole thinking line
    sys.stdout.flush()

    # The agent "types" its reply.
    sys.stdout.write(f"{GREEN}{BOLD}agent>{RESET}{GREEN} ")
    sys.stdout.flush()
    _type(reply, cps=120, newline=False)
    sys.stdout.write(f"{RESET}\n")
    sys.stdout.flush()

    # --- write BOTH sides of the turn back to memory (real persistence) ---
    agent.brain.write_memory("user", user_line, user_id)
    agent.brain.write_memory("assistant", reply, user_id)
    _pause(1.1)
    print()


def banner() -> None:
    line = "=" * 64
    print(f"{CYAN}{line}{RESET}")
    print(f"{BOLD}  SynapCores agent — live customer-support session{RESET}")
    print(f"{DIM}  brain = SynapCores  |  embeddings = OpenAI (1536-d)  |  LLM = gpt-4o{RESET}")
    print(f"{DIM}  recall (memory) + RAG (KB) + semantic tool-routing, every turn{RESET}")
    print(f"{CYAN}{line}{RESET}")
    print()
    _pause(1.0)


def main() -> None:
    config = Config.from_env()
    agent = SupportAgent(config)
    agent.setup()

    # Fresh, deterministic brain for the recording.
    agent.brain.wipe()
    agent.setup()
    counts = seed(agent.brain)

    uid = "acme-customer"

    banner()
    print(
        f"{DIM}Seeded {counts['kb_articles']} KB articles + "
        f"{counts['tickets']} resolved tickets into the brain.{RESET}"
    )
    print(f"{DIM}Customer: acme-customer  |  brain probed at "
          f"{agent.brain.embed_dim}-dim embeddings.{RESET}")
    print()
    _pause(1.4)

    # --- Turn 1: establishes a concrete detail to remember later ----------
    run_turn(
        agent, uid,
        "Hi, I'm on the Annual plan and I can't log in — it keeps saying my "
        "password is wrong.",
        beat="recall=0: first turn, nothing in memory yet. KB + past tickets ground the reply.",
    )

    # --- Turn 2: follow-up; agent should recall turn 1 from memory --------
    run_turn(
        agent, uid,
        "I tried resetting it but the reset email never arrived.",
        beat="recall>0: pulled the login problem back from memory by meaning, not keywords.",
    )

    # --- Turn 3: topic shift; routes to the KB ---------------------------
    run_turn(
        agent, uid,
        "Separately — if I cancel, can I get a refund on my annual subscription?",
        beat="semantic route swings to the KB: a how-to/policy question, not an incident.",
    )

    # --- Turn 4: THE memory beat — reference the earlier issue by meaning -
    run_turn(
        agent, uid,
        "Sorry, remind me — what were we troubleshooting earlier with my account?",
        beat="THE BEAT: no keyword overlap with 'login', yet it recalls the sign-in "
             "issue from memory and grounds the answer on it.",
    )

    # --- Turn 5: confirm continuity + the remembered plan detail ----------
    run_turn(
        agent, uid,
        "Right, that one. And which plan did I say I'm on?",
        beat="continuity: it remembers the Annual-plan detail from turn 1.",
    )

    line = "=" * 64
    print(f"{CYAN}{line}{RESET}")
    print(f"{BOLD}  agentic memory: it remembered across turns — by meaning.{RESET}")
    print(f"{DIM}  same agent, zero-key on the bundled model. see ../PRODUCTION.md{RESET}")
    print(f"{CYAN}{line}{RESET}")
    _pause(1.5)


if __name__ == "__main__":
    main()
